package com.csp.app.mapper;

import com.csp.app.entity.ExamGroup;

public interface ExamGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_group
     *
     * @mbg.generated
     */
    int insert(ExamGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_group
     *
     * @mbg.generated
     */
    int insertSelective(ExamGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_group
     *
     * @mbg.generated
     */
    ExamGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExamGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExamGroup record);
}