package com.csp.app.mapper;

import com.csp.app.entity.TestEntity;

public interface TestEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_entity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_entity
     *
     * @mbg.generated
     */
    int insert(TestEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_entity
     *
     * @mbg.generated
     */
    int insertSelective(TestEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_entity
     *
     * @mbg.generated
     */
    TestEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_entity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_entity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestEntity record);
}