package com.csp.app.entity;

import java.io.Serializable;
import java.util.Date;

public class Clasz implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clasz.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clasz.class_id
     *
     * @mbg.generated
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clasz.class_num
     *
     * @mbg.generated
     */
    private Integer classNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clasz.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clasz.to_school_year
     *
     * @mbg.generated
     */
    private Integer toSchoolYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clasz.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clasz
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clasz.id
     *
     * @return the value of clasz.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clasz.id
     *
     * @param id the value for clasz.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clasz.class_id
     *
     * @return the value of clasz.class_id
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clasz.class_id
     *
     * @param classId the value for clasz.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clasz.class_num
     *
     * @return the value of clasz.class_num
     *
     * @mbg.generated
     */
    public Integer getClassNum() {
        return classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clasz.class_num
     *
     * @param classNum the value for clasz.class_num
     *
     * @mbg.generated
     */
    public void setClassNum(Integer classNum) {
        this.classNum = classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clasz.create_time
     *
     * @return the value of clasz.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clasz.create_time
     *
     * @param createTime the value for clasz.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clasz.to_school_year
     *
     * @return the value of clasz.to_school_year
     *
     * @mbg.generated
     */
    public Integer getToSchoolYear() {
        return toSchoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clasz.to_school_year
     *
     * @param toSchoolYear the value for clasz.to_school_year
     *
     * @mbg.generated
     */
    public void setToSchoolYear(Integer toSchoolYear) {
        this.toSchoolYear = toSchoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clasz.type
     *
     * @return the value of clasz.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clasz.type
     *
     * @param type the value for clasz.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}