package com.csp.app.entity;

import java.io.Serializable;
import java.util.Date;

public class Exam implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_id
     *
     * @mbg.generated
     */
    private Integer examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_name
     *
     * @mbg.generated
     */
    private String examName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.student_count
     *
     * @mbg.generated
     */
    private Integer studentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_group_id
     *
     * @mbg.generated
     */
    private Integer examGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.exam_group_name
     *
     * @mbg.generated
     */
    private String examGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.id
     *
     * @return the value of exam.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.id
     *
     * @param id the value for exam.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.course_id
     *
     * @return the value of exam.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.course_id
     *
     * @param courseId the value for exam.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.course_name
     *
     * @return the value of exam.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.course_name
     *
     * @param courseName the value for exam.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.create_time
     *
     * @return the value of exam.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.create_time
     *
     * @param createTime the value for exam.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.end_time
     *
     * @return the value of exam.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.end_time
     *
     * @param endTime the value for exam.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_id
     *
     * @return the value of exam.exam_id
     *
     * @mbg.generated
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_id
     *
     * @param examId the value for exam.exam_id
     *
     * @mbg.generated
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_name
     *
     * @return the value of exam.exam_name
     *
     * @mbg.generated
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_name
     *
     * @param examName the value for exam.exam_name
     *
     * @mbg.generated
     */
    public void setExamName(String examName) {
        this.examName = examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.start_time
     *
     * @return the value of exam.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.start_time
     *
     * @param startTime the value for exam.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.student_count
     *
     * @return the value of exam.student_count
     *
     * @mbg.generated
     */
    public Integer getStudentCount() {
        return studentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.student_count
     *
     * @param studentCount the value for exam.student_count
     *
     * @mbg.generated
     */
    public void setStudentCount(Integer studentCount) {
        this.studentCount = studentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_group_id
     *
     * @return the value of exam.exam_group_id
     *
     * @mbg.generated
     */
    public Integer getExamGroupId() {
        return examGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_group_id
     *
     * @param examGroupId the value for exam.exam_group_id
     *
     * @mbg.generated
     */
    public void setExamGroupId(Integer examGroupId) {
        this.examGroupId = examGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.exam_group_name
     *
     * @return the value of exam.exam_group_name
     *
     * @mbg.generated
     */
    public String getExamGroupName() {
        return examGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.exam_group_name
     *
     * @param examGroupName the value for exam.exam_group_name
     *
     * @mbg.generated
     */
    public void setExamGroupName(String examGroupName) {
        this.examGroupName = examGroupName;
    }
}