package com.csp.app.entity;

import java.io.Serializable;
import java.util.Date;

public class ExamGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_group.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_group.exam_group_id
     *
     * @mbg.generated
     */
    private Integer examGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_group.exam_group_name
     *
     * @mbg.generated
     */
    private String examGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_group.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_group.id
     *
     * @return the value of exam_group.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_group.id
     *
     * @param id the value for exam_group.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_group.exam_group_id
     *
     * @return the value of exam_group.exam_group_id
     *
     * @mbg.generated
     */
    public Integer getExamGroupId() {
        return examGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_group.exam_group_id
     *
     * @param examGroupId the value for exam_group.exam_group_id
     *
     * @mbg.generated
     */
    public void setExamGroupId(Integer examGroupId) {
        this.examGroupId = examGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_group.exam_group_name
     *
     * @return the value of exam_group.exam_group_name
     *
     * @mbg.generated
     */
    public String getExamGroupName() {
        return examGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_group.exam_group_name
     *
     * @param examGroupName the value for exam_group.exam_group_name
     *
     * @mbg.generated
     */
    public void setExamGroupName(String examGroupName) {
        this.examGroupName = examGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_group.create_time
     *
     * @return the value of exam_group.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_group.create_time
     *
     * @param createTime the value for exam_group.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}