package com.csp.app.entity;

import java.io.Serializable;
import java.util.Date;

public class TestEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.answer_time
     *
     * @mbg.generated
     */
    private Long answerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.bill_duration
     *
     * @mbg.generated
     */
    private Integer billDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.bridge_duration
     *
     * @mbg.generated
     */
    private Integer bridgeDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.bridge_time
     *
     * @mbg.generated
     */
    private Long bridgeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.call_type
     *
     * @mbg.generated
     */
    private Integer callType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.callee_area_code
     *
     * @mbg.generated
     */
    private String calleeAreaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.callee_number
     *
     * @mbg.generated
     */
    private String calleeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.clid
     *
     * @mbg.generated
     */
    private String clid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.customer_city
     *
     * @mbg.generated
     */
    private String customerCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.customer_number
     *
     * @mbg.generated
     */
    private String customerNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.customer_province
     *
     * @mbg.generated
     */
    private String customerProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.detail_clid
     *
     * @mbg.generated
     */
    private String detailClid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.dial_time
     *
     * @mbg.generated
     */
    private Long dialTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.end_reason
     *
     * @mbg.generated
     */
    private Integer endReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.end_time
     *
     * @mbg.generated
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.mark
     *
     * @mbg.generated
     */
    private Integer mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.monitor_duration
     *
     * @mbg.generated
     */
    private Integer monitorDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.request_time
     *
     * @mbg.generated
     */
    private Long requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.start_time
     *
     * @mbg.generated
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.total_duration
     *
     * @mbg.generated
     */
    private Integer totalDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_entity.user_field
     *
     * @mbg.generated
     */
    private String userField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_entity
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.id
     *
     * @return the value of test_entity.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.id
     *
     * @param id the value for test_entity.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.answer_time
     *
     * @return the value of test_entity.answer_time
     *
     * @mbg.generated
     */
    public Long getAnswerTime() {
        return answerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.answer_time
     *
     * @param answerTime the value for test_entity.answer_time
     *
     * @mbg.generated
     */
    public void setAnswerTime(Long answerTime) {
        this.answerTime = answerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.bill_duration
     *
     * @return the value of test_entity.bill_duration
     *
     * @mbg.generated
     */
    public Integer getBillDuration() {
        return billDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.bill_duration
     *
     * @param billDuration the value for test_entity.bill_duration
     *
     * @mbg.generated
     */
    public void setBillDuration(Integer billDuration) {
        this.billDuration = billDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.bridge_duration
     *
     * @return the value of test_entity.bridge_duration
     *
     * @mbg.generated
     */
    public Integer getBridgeDuration() {
        return bridgeDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.bridge_duration
     *
     * @param bridgeDuration the value for test_entity.bridge_duration
     *
     * @mbg.generated
     */
    public void setBridgeDuration(Integer bridgeDuration) {
        this.bridgeDuration = bridgeDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.bridge_time
     *
     * @return the value of test_entity.bridge_time
     *
     * @mbg.generated
     */
    public Long getBridgeTime() {
        return bridgeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.bridge_time
     *
     * @param bridgeTime the value for test_entity.bridge_time
     *
     * @mbg.generated
     */
    public void setBridgeTime(Long bridgeTime) {
        this.bridgeTime = bridgeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.call_type
     *
     * @return the value of test_entity.call_type
     *
     * @mbg.generated
     */
    public Integer getCallType() {
        return callType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.call_type
     *
     * @param callType the value for test_entity.call_type
     *
     * @mbg.generated
     */
    public void setCallType(Integer callType) {
        this.callType = callType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.callee_area_code
     *
     * @return the value of test_entity.callee_area_code
     *
     * @mbg.generated
     */
    public String getCalleeAreaCode() {
        return calleeAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.callee_area_code
     *
     * @param calleeAreaCode the value for test_entity.callee_area_code
     *
     * @mbg.generated
     */
    public void setCalleeAreaCode(String calleeAreaCode) {
        this.calleeAreaCode = calleeAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.callee_number
     *
     * @return the value of test_entity.callee_number
     *
     * @mbg.generated
     */
    public String getCalleeNumber() {
        return calleeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.callee_number
     *
     * @param calleeNumber the value for test_entity.callee_number
     *
     * @mbg.generated
     */
    public void setCalleeNumber(String calleeNumber) {
        this.calleeNumber = calleeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.clid
     *
     * @return the value of test_entity.clid
     *
     * @mbg.generated
     */
    public String getClid() {
        return clid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.clid
     *
     * @param clid the value for test_entity.clid
     *
     * @mbg.generated
     */
    public void setClid(String clid) {
        this.clid = clid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.create_time
     *
     * @return the value of test_entity.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.create_time
     *
     * @param createTime the value for test_entity.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.customer_city
     *
     * @return the value of test_entity.customer_city
     *
     * @mbg.generated
     */
    public String getCustomerCity() {
        return customerCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.customer_city
     *
     * @param customerCity the value for test_entity.customer_city
     *
     * @mbg.generated
     */
    public void setCustomerCity(String customerCity) {
        this.customerCity = customerCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.customer_number
     *
     * @return the value of test_entity.customer_number
     *
     * @mbg.generated
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.customer_number
     *
     * @param customerNumber the value for test_entity.customer_number
     *
     * @mbg.generated
     */
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.customer_province
     *
     * @return the value of test_entity.customer_province
     *
     * @mbg.generated
     */
    public String getCustomerProvince() {
        return customerProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.customer_province
     *
     * @param customerProvince the value for test_entity.customer_province
     *
     * @mbg.generated
     */
    public void setCustomerProvince(String customerProvince) {
        this.customerProvince = customerProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.detail_clid
     *
     * @return the value of test_entity.detail_clid
     *
     * @mbg.generated
     */
    public String getDetailClid() {
        return detailClid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.detail_clid
     *
     * @param detailClid the value for test_entity.detail_clid
     *
     * @mbg.generated
     */
    public void setDetailClid(String detailClid) {
        this.detailClid = detailClid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.dial_time
     *
     * @return the value of test_entity.dial_time
     *
     * @mbg.generated
     */
    public Long getDialTime() {
        return dialTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.dial_time
     *
     * @param dialTime the value for test_entity.dial_time
     *
     * @mbg.generated
     */
    public void setDialTime(Long dialTime) {
        this.dialTime = dialTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.end_reason
     *
     * @return the value of test_entity.end_reason
     *
     * @mbg.generated
     */
    public Integer getEndReason() {
        return endReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.end_reason
     *
     * @param endReason the value for test_entity.end_reason
     *
     * @mbg.generated
     */
    public void setEndReason(Integer endReason) {
        this.endReason = endReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.end_time
     *
     * @return the value of test_entity.end_time
     *
     * @mbg.generated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.end_time
     *
     * @param endTime the value for test_entity.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.mark
     *
     * @return the value of test_entity.mark
     *
     * @mbg.generated
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.mark
     *
     * @param mark the value for test_entity.mark
     *
     * @mbg.generated
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.monitor_duration
     *
     * @return the value of test_entity.monitor_duration
     *
     * @mbg.generated
     */
    public Integer getMonitorDuration() {
        return monitorDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.monitor_duration
     *
     * @param monitorDuration the value for test_entity.monitor_duration
     *
     * @mbg.generated
     */
    public void setMonitorDuration(Integer monitorDuration) {
        this.monitorDuration = monitorDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.request_time
     *
     * @return the value of test_entity.request_time
     *
     * @mbg.generated
     */
    public Long getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.request_time
     *
     * @param requestTime the value for test_entity.request_time
     *
     * @mbg.generated
     */
    public void setRequestTime(Long requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.start_time
     *
     * @return the value of test_entity.start_time
     *
     * @mbg.generated
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.start_time
     *
     * @param startTime the value for test_entity.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.status
     *
     * @return the value of test_entity.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.status
     *
     * @param status the value for test_entity.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.total_duration
     *
     * @return the value of test_entity.total_duration
     *
     * @mbg.generated
     */
    public Integer getTotalDuration() {
        return totalDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.total_duration
     *
     * @param totalDuration the value for test_entity.total_duration
     *
     * @mbg.generated
     */
    public void setTotalDuration(Integer totalDuration) {
        this.totalDuration = totalDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_entity.user_field
     *
     * @return the value of test_entity.user_field
     *
     * @mbg.generated
     */
    public String getUserField() {
        return userField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_entity.user_field
     *
     * @param userField the value for test_entity.user_field
     *
     * @mbg.generated
     */
    public void setUserField(String userField) {
        this.userField = userField;
    }
}