server:
  port: 8085
  compression:
    enabled: true
    min-response-size: 20480
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript
  tomcat:
    uri-encoding: utf-8
spring.thymeleaf.mode: HTML
spring.thymeleaf.encodin: UTF-8
spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url:
#    username:
#    password:
    filters: stat,wall,config,slf4j
    max-active: 50
    initial-size: 1
    max-wait: 60000
    min-idle: 10


  redis:
    host: 47.103.3.1
    port: 6379
    password:
    database: 0
    timeout: 3000
    jedis:
      pool:
        max-idle: 80
        min-idle: 50
        max-total: 100
#自动建表配置
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#jest
jest:
  host: http://localhost:9200
  maxTotalConnectionPerRoute: 100
  maxTotalConnection: 100
  userName:
  password:

mybatis:
  type-aliases-package: com.csp.app.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#常用sql查询
mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    typeAliasesPackage: com.csp.app.entity
    db-column-underline: true




